export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE ='FETCH_DATA_FAILURE';
export const FETCH_PAGINATION_DATA_SUCCESS ='FETCH_PAGINATION_DATA_SUCCESS';
export const FETCH_ITEM_DETAIL_SUCCESS ='FETCH_ITEM_DETAIL_SUCCESS';